### ISSUE TITLE
升档模块

### ISSUE THREAD

**Issue by funnyJackPeng** [funnyJackPeng/yukunyuan-tools-feature#1]
模块名称：提升捐助金额反馈
业务说明：
### 1、原内容举例说明
收件人： [cxgy12@126.com](mailto:cxgy12@126.com)  （此地址为升档时，发给社区的固定邮箱地址，不能更改）
邮件主题：13012345670周3241由原来的5000升级到30000
邮件正文：不需要，留空即可
### 2、小工具内显示给用户的内容（加括号部分要留空，由用户自己手动填写，没有加括号部分是固定内容，要在程序中写出来，不能做任何修改）
收件人： [cxgy12@126.com](mailto:cxgy12@126.com)  （此地址为升档时，发给社区的固定邮箱地址，不能更改）
邮件主题：（      ）由原来的（      ）升级到（      ）
邮件正文：不需要，留空即可

## 前端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/15
## 后端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-backend/issues/12

**Comment by hk6888** [comment]
收件邮箱改一下 ，改成以下邮箱地址
提升捐助金额申请：cxgy12@126.com

**Comment by hk6888** [comment]
修改完收件箱地址后，升档模块测试就完成了

**Comment by hk6888** [comment]
收件邮箱地址我已修改，等待测试

**Comment by hk6888** [comment]
1、原内容举例说明
收件人：cxgy12@126.com（此地址为升档时，发给社区的固定邮箱地址，不能更改）
邮件主题：13012345670周3241由原来的5000升级到30000
邮件正文：不需要，留空即可

2、小工具内显示给用户的内容（加括号部分要留空，由用户自己手动填写，没有加括号部分是固定内容，要在程序中写出来，不能做任何修改）
收件人： [cxgy12@126.com](mailto:cxgy12@126.com) （此地址为升档时，发给社区的固定邮箱地址，不能更改）
邮件主题：（ ）由原来的（ ）升级到（ ）
邮件正文：不需要，留空即可

**Comment by funnyJackPeng** [comment]
收件地址目前是直接写到数据库中的，不需要修改代码
