### ISSUE TITLE
`我的` 页面中，在昵称下面显示绑定的邮箱，如果还没有绑定，则进入页面时给出提示

### ISSUE THREAD

**Issue by funnyJackPeng** [funnyJackPeng/yukunyuan-tools-feature#10]
## 前端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/18
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/19

## 后端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-backend/issues/16

**Comment by hk6888** [comment]
绑定邮箱显示在我的头像下面，不要显示在昵称后面
