### ISSUE TITLE
修改模版时，默认内容填入空字符串或者 0 

### ISSUE THREAD

**Issue by funnyJackPeng** [funnyJackPeng/yukunyuan-tools-feature#17]
![image](https://github.com/user-attachments/assets/9dd952f5-6cb3-45da-a960-4f9f27bdf55c)

即这里默认显示灰色的提示语，点进去后消失不见，而不是需要手动删除

## 前端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/24

**Comment by hk6888** [comment]
对，只要退出来，灰色提示又自动显示出来。
第二种方式：直接显示灰色提示不消失，用户点进去后，可以直接在上面用上浮显示的方式输入自己的内容，这样，用户即使在输入状态下，依然可以看到灰色的提示语。这种方式，用户的体验感应该更好。（鲸鱼就是用的这种方式）
你看看，用哪种方式，你那边合理安排即可。

**Comment by funnyJackPeng** [comment]
这里的 `提示语` 其实每行前面的标签已经填入了，后面的内容应该是用户保存的信息。
举个例子:
`推荐人编号` 这一栏，前面已经说了这一栏该填入什么，后面的内容应该是用户上一次填入然后保存的信息，而不是又是提示信息。
只不过第一次进入的时候应该留空

**Comment by hk6888** [comment]
好的，我只是提出这个需求，至于如何实施，你定了就作数
