### ISSUE TITLE
QQ邮箱测试中，只有860388850在已发送里能看到发送邮件，其他QQ邮箱里都没有记录

### ISSUE THREAD

**Issue by hk6888** [funnyJackPeng/yukunyuan-tools-feature#20]

**Comment by funnyJack** [comment]
![image](https://github.com/user-attachments/assets/485f7cb8-84ba-4f4e-b5ea-ecd94f41a7a4)
已解决，需要在 QQ 邮箱的 SMTP 设置出开启 `SMTP发信后保存到服务器` 选项

**Comment by hk6888** [comment]
收到，已发给客户，客户已学会设置，问题已解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月30日 20:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [funnyJackPeng/yukunyuan-tools-feature] QQ邮箱测试中，只有860388850在已发送里能看到发送邮件，其他QQ邮箱里都没有记录 (Issue #20) |

Closed #20 as completed.
