### ISSUE TITLE
加入申请模块

### ISSUE THREAD

**Issue by funnyJackPeng** [funnyJackPeng/yukunyuan-tools-feature#3]
模块名称：加入申请
业务说明：
## 1、原内容举例说明
收件人：[gyd2345@163.com](mailto:gyd2345@163.com) （此地址为报单时，发给社区的固定邮箱地址，不能更改）
邮件主题：13012345117周1034推13088881234胡5002加30000
邮件正文：
诚信共赢社区管理处：
我姓胡，女性，昵称“佛渡有缘人”；居住地三亚。现申请加入诚信共赢社区，特声明如下：
      1.认同互助思想理念，遵守诚信共赢社区相关规定。
      2.拥护诚信共赢社区指导方针：“无偿援助，互惠和仁爱”。
      3.明白“参与诚信共赢社区，本身就是愿意提供无偿援助的明确表示”，认同社区共识“参与社区等于自愿捐助”。
      4.承诺闲钱参与，不动用关键资金，绝不借贷参与。
      5.承诺不利用诚信共赢平台从事任何政治、宗教、黄赌毒及其他犯罪活动；不攻击、诽谤任何国家、政府、政党、组织、企业或个人。
      6.阅读了警告，完全了解所有风险，决定参与诚信共赢社区。本人心智健全，具有完全民事行为能力，能对自己的行为完全负责，即使有资金损失，也完全由自己负责，决不怪罪任何人。
      申请人：13088881234胡5002
      推荐人：13012345117周1034

                                                                                                                                   二〇二四年八月十七日
## 2、小工具内显示给用户的内容（加括号部分要留空，由用户自己手动填写，没有加括号部分是固定内容，要在程序中写出来，不能做任何修改）
收件人：[gyd2345@163.com](mailto:gyd2345@163.com) （这个在小工具中显示出来，不能做任何修改）
邮件主题：（  ）推（  ）加（  ）
邮件正文：
诚信共赢社区管理处：
我姓（  ），（  ）性，昵称（  ）；居住地（  ）。现申请加入诚信共赢社区，特声明如下：
      1.认同互助思想理念，遵守诚信共赢社区相关规定。
      2.拥护诚信共赢社区指导方针：“无偿援助，互惠和仁爱”。
      3.明白“参与诚信共赢社区，本身就是愿意提供无偿援助的明确表示”，认同社区共识“参与社区等于自愿捐助”。
      4.承诺闲钱参与，不动用关键资金，绝不借贷参与。
      5.承诺不利用诚信共赢平台从事任何政治、宗教、黄赌毒及其他犯罪活动；不攻击、诽谤任何国家、政府、政党、组织、企业或个人。
      6.阅读了警告，完全了解所有风险，决定参与诚信共赢社区。本人心智健全，具有完全民事行为能力，能对自己的行为完全负责，即使有资金损失，也完全由自己负责，决不怪罪任何人。
      申请人：（      ）
      推荐人：（      ）
                                                                                                                                  （  ）年（  ）月（  ）日

### 前端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/8
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/21

### 后端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-backend/issues/4
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-backend/issues/13
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-backend/issues/17

**Comment by hk6888** [comment]
test

**Comment by hk6888** [comment]
邮件主题：（ ）推（ ）加（ ），这三个括号说明
    第一个（）需要填写推荐人的完整编号：比如：16676865999贺1496，在小程序中显示备注信息给用户：填写推荐人完整编号

    第二个（）需要填写自己的完整编号：比如：13388883711贺9897，在小程序中显示备注信息给用户：填写自己的完整编号

    第三个（）需要填写自己报单的具体金额：比如：30000，这个括号要加以限制，只能填写1000-30000之间的纯数字，数字位数限制在4-5位数之间，少于4位或多于5位的数字禁止填入，在小程序中显示备注信息给用户：填写报单金额

**Comment by hk6888** [comment]
申请人：（ ）（显示给用户备注信息：填写自己的完整编号）
推荐人：（ ）（显示给用户备注信息：填写推荐人的完整编号）

**Comment by hk6888** [comment]
申请人：（   ）
推荐人：（   ）
这两个括号需要显示给用户的备注信息说明如下：
申请人：（   ）填写自己完整的编号
推荐人：（   ）填写推荐人完整的编号

**Comment by hk6888** [comment]
邮件主题：（ ）推（ ）加（ ），这三个括号说明

第一个（ ）需要填写推荐人的完整编号：比如：16676865999贺1496，在小程序中显示备注信息给用户：填写推荐人的完整编号

第二个（）需要填写自己的完整编号：比如：13388883711贺9897，在小程序中显示备注信息给用户：填写自己的完整编号

第三个（）需要填写自己报单的具体金额：比如：30000，这个括号要加以限制，只能填写1000-30000之间的纯数字，数字位数限制在4-5位数之间，少于少于4位或多于5位的数字禁止填入，在小程序中显示备注信息给用户：填写报单金额

**Comment by hk6888** [comment]
邮件主题：（ ）推（ ）加（ ），这三个括号说明

第一（）填写推荐人的完整编号：比如：16676865999贺1496，在小程序中显示备注信息给用户：填写推荐人的完整编号

第二（）填写自己的完整编号：比如：13388883711贺9897，在小程序中显示备注信息给用户：填写自己的完整编号

第三个（）填写自己报单的具体金额：比如：30000，这个括号要引用限制，只能填写1000-30000之间的纯数字，数字位数限制在4-5位数之间，少于少于4位或多于5位的数字禁止填入，在小程序中显示备注信息给用户：填写报单金额

**Comment by hk6888** [comment]
申请人：（ ）
推荐人：（ ）
此处两个括号给用户显示的备注信息说明：
申请人：（ ）（填写自己的完整编号）
推荐人：（ ）（填写推荐人的完整编号）

**Comment by hk6888** [comment]
![加入申请最终显示效果图](https://github.com/funnyJackPeng/yukunyuan-tools-feature/assets/173553775/3183b019-81bf-4958-965a-391396d96a9e)

这是加入申请邮件发送时显示的最终结果及排版样式，在发送前，小程序再给用户出现一个以下对话框

       请再次核对邮件内容，是否确定发送？

         否，需要修改        是，内容正确，确定发送

**Comment by funnyJackPeng** [comment]
金额必须保留到个位，不需要小数部分，否则诚信那边识别不到

**Comment by hk6888** [comment]
可以阔以阔以



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月10日 21:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [funnyJackPeng/yukunyuan-tools-feature] 加入申请模块 (Issue #3) |

金额必须保留到个位，不需要小数部分，否则诚信那边识别不到

**Comment by funnyJackPeng** [comment]
金额改成 1000 - 30000，其他模块一样

**Comment by hk6888** [comment]
我已把最上面的两个框里的原内容全部修改成2024年8月的最新修改内容，原来的内容已全部覆盖，现在最上面的  1、原内容举例说明   2、小工具内显示给用户的内容（加括号部分要留空，由用户自己手动填写，没有加括号部分是固定内容，要在程序中写出来，不能做任何修改）  以我现在修改后的这两个框中所显示的内容为准

**Comment by hk6888** [comment]
申请内容我已修改成2024年8月的最新内容，等待测试

**Comment by hk6888** [comment]
收件人：gyd2345@163.com（此地址为报单时，发给社区的固定邮箱地址，不能更改）
邮件主题：13012345117周1034推13088881234胡5002加30000
邮件正文：
诚信共赢社区管理处：
我姓胡，女性，昵称“佛渡有缘人”；居住地三亚。现申请加入诚信共赢社区，特声明如下：
1.认同互助思想理念，遵守诚信共赢社区相关规定。
2.拥护诚信共赢社区指导方针：“无偿援助，互惠和仁爱”。
3.明白“参与诚信共赢社区，本身就是愿意提供无偿援助的明确表示”，认同社区共识“参与社区等于自愿捐助”。
4.承诺闲钱参与，不动用关键资金，绝不借贷参与。
5.承诺不利用诚信共赢平台从事任何政治、宗教、黄赌毒及其他犯罪活动；不攻击、诽谤任何国家、政府、政党、组织、企业或个人。
6.阅读了警告，完全了解所有风险，决定参与诚信共赢社区。本人心智健全，具有完全民事行为能力，能对自己的行为完全负责，即使有资金损失，也完全由自己负责，决不怪罪任何人。
申请人：13088881234胡5002
推荐人：13012345117周1034
2024年8月19日

**Comment by hk6888** [comment]
收件人：gyd2345@163.com（这个在小工具中显示出来，不能做任何修改）
邮件主题：（ ）推（ ）加（ ）
邮件正文：
诚信共赢社区管理处：
我姓（ ），（ ）性，昵称（ ）；居住地（ ）。现申请加入诚信共赢社区，特声明如下：
1.认同互助思想理念，遵守诚信共赢社区相关规定。
2.拥护诚信共赢社区指导方针：“无偿援助，互惠和仁爱”。
3.明白“参与诚信共赢社区，本身就是愿意提供无偿援助的明确表示”，认同社区共识“参与社区等于自愿捐助”。
4.承诺闲钱参与，不动用关键资金，绝不借贷参与。
5.承诺不利用诚信共赢平台从事任何政治、宗教、黄赌毒及其他犯罪活动；不攻击、诽谤任何国家、政府、政党、组织、企业或个人。
6.阅读了警告，完全了解所有风险，决定参与诚信共赢社区。本人心智健全，具有完全民事行为能力，能对自己的行为完全负责，即使有资金损失，也完全由自己负责，决不怪罪任何人。
申请人：（ ）
推荐人：（ ）
（ ）年（ ）月（ ）日（这里的日期可以使用系统识别的日期）
