### ISSUE TITLE
捐助申请模块

### ISSUE THREAD

**Issue by funnyJackPeng** [funnyJackPeng/yukunyuan-tools-feature#4]
模块名称：捐助申请
业务说明：
### 1、原内容举例说明
收件人：chengxin202112@163.com （此地址为排单时，发给社区的固定邮箱地址，不能更改）
邮件主题：13800000000李5678申请捐助30000(2)
邮件正文：
诚信共赢社区管理处：
本人自愿申请捐助30000元。
本人阅读了警告，完全了解所有风险，决定参与诚信共赢社区。
本人心智健全，具有完全民事行为能力，能对自己的行为完全负责。即使有资金损失，也完全由自己负责，决不怪罪任何人。
申请人：13800000000李5678
推荐人：13600000000王1234
二〇二四年八月十八日

### 2、小工具内显示给用户的内容（加括号部分要留空，由用户自己手动填写，没有加括号部分是固定内容，要在程序中写出来，不能做任何修改）
收件人：chengxin202112@163.com （此地址为排单时，发给社区的固定邮箱地址，不能更改）
邮件主题：（      ）申请捐助（      ）（      ）
邮件正文：
诚信共赢社区管理处：
本人自愿申请捐助（      ）元。
本人阅读了警告，完全了解所有风险，决定参与诚信共赢社区。
本人心智健全，具有完全民事行为能力，能对自己的行为完全负责。即使有资金损失，也完全由自己负责，决不怪罪任何人。
申请人：（      ）
推荐人：（      ）
（      ）年（      ）月（      ）日（这里的日期可以使用系统自动识别的日期）

### 前端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/13
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/22
### 后端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-backend/issues/9
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-backend/issues/18

**Comment by hk6888** [comment]
邮件主题：（ ）申请捐助（ ）（ ）
前两个（）跟以前一样，不做修改，现在增加了第三个（），第三个（）的提示语：捐助单序号

     所有内容我已同步到2024年8月诚信的最新修改内容，邮件主题后面增加了第三个（），需要在小程序中同步增加

**Comment by hk6888** [comment]
所有内容我已同步到2024年8月诚信的最新修改内容，邮件主题后面增加了第三个（），需要在小程序中同步增加

**Comment by hk6888** [comment]
申请加入默认为申请捐助的第一单；从第二单开始，申请捐助订单要在金额后面的括号里写上顺序号，如（2）、（3）、（4）.. .. ..每位家人的场外等候捐助订单不得超过3个
    这是诚信公告中对第三个（）的具体说明

**Comment by hk6888** [comment]
1、原内容举例说明
收件人：chengxin202112@163.com（此地址为排单时，发给社区的固定邮箱地址，不能更改）
邮件主题：13800000000李5678申请捐助30000(2)（这个括号要使用英文状态下的括号）
邮件正文：
诚信共赢社区管理处：
本人自愿申请捐助30000元。
本人阅读了警告，完全了解所有风险，决定参与诚信共赢社区。
本人心智健全，具有完全民事行为能力，能对自己的行为完全负责。即使有资金损失，也完全由自己负责，决不怪罪任何人。
申请人：13800000000李5678
推荐人：13600000000王1234
二〇二四年八月十八日

2、小工具内显示给用户的内容（加括号部分要留空，由用户自己手动填写，没有加括号部分是固定内容，要在程序中写出来，不能做任何修改）
收件人：[chengxin202112@163.com](mailto:chengxin202112@163.com) （此地址为排单时，发给社区的固定邮箱地址，不能更改）
邮件主题：(    )申请捐助(    )(    )(这里的括号要使用英文状态下的括号)
邮件正文：
诚信共赢社区管理处：
本人自愿申请捐助（ ）元。
本人阅读了警告，完全了解所有风险，决定参与诚信共赢社区。
本人心智健全，具有完全民事行为能力，能对自己的行为完全负责。即使有资金损失，也完全由自己负责，决不怪罪任何人。
申请人：（ ）
推荐人：（ ）
（ ）年（ ）月（ ）日（这里的日期可以使用系统自动识别的日期）

**Comment by hk6888** [comment]
申请加入默认为申请捐助的第一单；从第二单开始，申请捐助订单要在金额后面的括号里写上顺序号，如（2）、（3）、（4）.. .. ..每位家人的场外等候捐助订单不得超过3个
这是诚信公告中对第三个括号的具体说明

**Comment by hk6888** [comment]
邮件主题：13800000000李5678申请捐助30000(2)
后面这个括号要保留英文格式的括号，括号里留空，排单序号由用户自己填写。括号里的提示语：排单序号
排单序号系统默认用户的加入申请单为(1)，所以，用户自己排单的第一单就是第二单了。以下是操作手册里的说明：
申请加入默认为申请捐助的第一单；从第二单开始，申请捐助订单要在金额后面的括号里写上顺序号，如（2）、（3）、（4）.. .. ..每位家人的场外等候捐助订单不得超过3个
