### ISSUE TITLE
受助申请模块

### ISSUE THREAD

**Issue by funnyJackPeng** [funnyJackPeng/yukunyuan-tools-feature#5]
模块名称：受助申请
业务说明：
### 1、原内容举例说明
收件人：[shouzhu2024@163.com](mailto:shouzhu2024@163.com) （此地址为提现时，发给社区的固定邮箱地址，不能更改）
邮件主题：13012345670周3241申请受助30000加（230703）
邮件正文：不需要，留空即可
### 2、小工具内显示给用户的内容（加括号部分要留空，由用户自己手动填写，没有加括号部分是固定内容，要在程序中写出来，不能做任何修改）
收件人：[shouzhu2024@163.com](mailto:shouzhu2024@163.com)  （此地址为提现时，发给社区的固定邮箱地址，不能更改）
邮件主题：（      ）申请受助（      ）加（      ）
邮件正文：不需要，留空即可

## 前端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/14
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-mini/issues/23
## 后端
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-backend/issues/11
- [x] https://github.com/funnyJackPeng/yukunyuan-tools-backend/issues/19

**Comment by hk6888** [comment]
邮件主题：（ ）申请受助（ ）加（ ）
1、三个（）由用户自己填写，第一个（）里提示语：自己的编号，第二个（）提示语：捐金额；第三个（）提示语：捐日期
2、主题中，申请受助   与   加   是固定用语，不允许用户自行修改

**Comment by hk6888** [comment]
收件邮箱需要修改成以下地址
受助申请：shouzhu2024@163.com.

**Comment by hk6888** [comment]
收件邮箱地址我已修改，等待测试

**Comment by hk6888** [comment]
1、原内容举例说明
收件人：shouzhu2024@163.com（此地址为提现时，发给社区的固定邮箱地址，不能更改）
邮件主题：13012345670周3241申请受助30000加(230703)
邮件正文：不需要，留空即可

2、小工具内显示给用户的内容（加括号部分要留空，由用户自己手动填写，没有加括号部分是固定内容，要在程序中写出来，不能做任何修改）
收件人：[shouzhu2024@163.com](mailto:shouzhu2024@163.com) （此地址为提现时，发给社区的固定邮箱地址，不能更改）
邮件主题：(   )申请受助(   )加(   )
邮件正文：不需要，留空即可
注意：括号要使用输入法在英文状态下的括号
